### ISSUE TITLE
Refresh button clears the form

### ISSUE THREAD

**Issue by TomJLynch** [metronical/metron#120]
Open a form from the list.  You'll see the data in the fields, as you should.  You'll see the URL ends with something like "#/Form/ItemID=50".  If you click the browser's refresh button, the page reloads and the URL loses the "ItemID=50" and only ends with "#/Form/".  All the data in the form's fields disappear.

**Comment by TomJLynch** [comment]
This also seems to affect trying to reach a form with a direct URL.  For example, a link in an email to a specific record.  The form section loads appropriately, but the URL loses the ID parameter and no data is loaded into the form.

**Comment by szul** [comment]
Wasn’t the case previously. Sounds like a bug got introduced somewhere. I’ll have to take a look.

________________________________
