### ISSUE TITLE
Filters don't pass data-m-key

### ISSUE THREAD

**Issue by TomJLynch** [metronical/metron#125]
On line 135 of metron.lists.ts the variable key can be set to attribute data-m-key instead of the default attribute name.  I took advantage of that to fix a filter whose source data didn't have a column name that matched the name attribute, causing it to fill the select option values with "undefined".  However, the on change event handler for the filter doesn't realize that the select element's data-m-key may be different than the name attribute.  It's necessary to submit a filtered request using the name attribute, because that name matches the filter parameter on Get method in the web service.  So, if you use a data-m-key that doesn't match the name, the Get call doesn't receive a value in the desired filter parameter.  

Don't allow the use of data-m-key?  Or force the key in fil[key] to always be the name attribute?  Something else?

**Comment by szul** [comment]
Added warning prior to connecting to the API endpoint.
