### ISSUE TITLE
Required Checkbox breaks form's IsValid

### ISSUE THREAD

**Issue by TomJLynch** [metronical/metron#129]
I gave a checkbox the required=required attribute.  When IsValid runs after clicking save, it crashes on line 266.  Stepping through in Visual Studio didn't give me an error, the execution just stops.  Stepping through in Chrome debugger identifies (<HTMLElement>elem).val().trim() === "" as the problem, with an error something like trim() not be valid on the type.

**Comment by szul** [comment]
Added exception handling around the validity checks. Will log to console if an invalid check is made.
